[package]
name = "qsync-macro"
version = "0.1.0"
edition = "2021"
description = "Macros for qsync (see https://github.com/Wulf/qsync)"
license = "MIT OR Apache-2.0"
readme = "../README.md"

[lib]
proc-macro = true
name = "qsync_macro"
path = "src/lib.rs"

[dependencies]